input:
  filepath: /home/carbonati/workspace/kaggle-melanoma/data/train.csv
  duplicate_path: /home/carbonati/workspace/kaggle-melanoma/data/sus/2020_Challenge_duplicates.csv

output:
  root: /home/carbonati/workspace/kaggle-melanoma/data/cv_folds

cv_folds:
  test_size: 0
  num_folds: 10
  index_col: patient_id
  stratify_val:
    - malignant_rate
    - num_images
    - anatom_site_general_challenge
  random_state: 42069

preprocess:
  malignant_rate:
    n_bins: 12
    strategy: kmeans
    apply_log: true
  num_images:
    n_bins: 10
    strategy: quantile
    apply_log: true
