input:
  data_dir: /home/carbonati/workspace/kaggle-melanoma/data/
  root: /home/carbonati/workspace/kaggle-melanoma/data/jpeg

output:
  output_dir: /home/carbonati/workspace/kaggle-melanoma/data/ISIC_2020_meta_fix

data:
  size: 300
  interpolation: 4
  quality: 100
  img_format: jpg

default:
  return_meta: true
