input:
  train: /workspace/data/train.csv
  test: /workspace/data/test.csv
  model: /workspace/models/arch_exp_1/efficientnet-b7_bce_smth_300_8_concat_adam_one_cycle_20200807_1618

output:
  predictions: /workspace/predictions

step: val_roc_auc_score
eval_train: true
eval_val: false
eval_test: false
num_bags: 1
tta: false
batch_size: 128
keep_prob: 1
num_workers: 16
random_state: 42069
device_ids:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
