input:
  test: /workspace/data/test.csv
  #train: /workspace/data/train.csv
  #test: /workspace/data/test.csv
  #model: /workspace/models/batch_sampler_fix_exp_1/efficientnet-b5_bce_smth_300_16_concat_adam_one_cycle_20200810_0203

output:
  predictions: /workspace/predictions

step: val_roc_auc_score
# eval_train: true
eval_val: false # jtrue
eval_test: true
eval_holdout: false # true
num_bags: 20
tta: true
batch_size: 4096
keep_prob: 1
num_workers: 16
random_state: 42069
device_ids:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
