input:
  {}
  # model: /root/workspace/kaggle-melanoma/models/misc_exp_1/efficientnet-b0_bce_224_64_concat_adam_one_cycle_20200731_1458

output:
  predictions: /root/workspace/kaggle-melanoma/predictions

step: val_roc_auc_score
eval_val: true
eval_train: true
eval_holdout: true
eval_test: true
tta: false
num_bags: 1
batch_size: 256
keep_prob: 1
num_workers: 8
random_state: 42069
